import{y as S,s as w,E as x,g as T,a as F,b as M,c as I}from"./assets/main-CJH0_9VY.js";/* empty css                      */import{i as E,A as q}from"./assets/vendor-4jich7g5.js";const R=async i=>(await S.get("/filters",{params:i})).data,m="dots",l="prev",g="next",u="first",d="last",c=3;class B{constructor(e,t){this.container=e,this.pagination=t,this.initListeners()}render(){this.container.innerHTML="";const e=this.pagination.getPages(),t=this.pagination.getCurrentPage(),s=this.pagination.getTotalPages(),a=t===1,n=t===s;let r="";e.length>c&&(r+=this.createPageTemplate(u,a),r+=this.createPageTemplate(l,a)),e.forEach(o=>{typeof o=="number"?r+=this.createPageTemplate(o,!1,o===t):r+=this.createPageTemplate(o,!0)}),e.length>c&&(r+=this.createPageTemplate(g,n),r+=this.createPageTemplate(d,n)),this.container.innerHTML=`<ul class="pagination">${r}</ul>`}clear(){this.container.innerHTML=""}initListeners(){this.container.addEventListener("click",e=>{const s=e.target.closest(".page-btn");s&&(s.dataset.page===l?this.pagination.prevPage():s.dataset.page===g?this.pagination.nextPage():s.dataset.page===u?this.pagination.firstPage():s.dataset.page===d?this.pagination.lastPage():this.pagination.setPage(+s.dataset.page))})}createPageTemplate(e,t=!1,s=!1){const a=[];return s&&a.push("page-btn--active"),typeof e=="string"&&a.push(`page-btn--${e}`),`<li class="pagination__item">
      <button class="page-btn ${a.join(" ")}" ${t?'disabled="disabled"':""} data-page="${e}">${this.createPageContent(e)}</button>
    </li>`}createPageContent(e){if(typeof e=="number")return e.toString();if(e===m)return"...";const t={[u]:"icon-arw-2-left",[d]:"icon-arw-2-right",[l]:"icon-arw-left",[g]:"icon-arw-right"}[e];return`<svg class="page-icon"><use href="${w}#${t}"></use></svg>`}}class C{constructor(e,t,s,a=1){this.totalPages=t,this.itemsPerPage=s,this.currentPage=a,this.listeners=[],this.view=new B(e,this),this.view.render()}setPage(e){e<1||e>this.totalPages||e===this.currentPage||(this.currentPage=e,this.notifyListeners())}setTotalPages(e){this.totalPages=e,this.view.render()}nextPage(){this.setPage(this.currentPage+1)}prevPage(){this.setPage(this.currentPage-1)}lastPage(){this.setPage(this.totalPages)}firstPage(){this.setPage(1)}getPages(){const e=[];if(this.totalPages<=c)for(let t=1;t<=this.totalPages;t++)e.push(t);else{this.currentPage>c-1&&e.push(m);const t=Math.max(1,Math.min(this.currentPage-1,this.totalPages-c+1)),s=Math.min(this.totalPages,Math.max(this.currentPage+1,c));for(let a=t;a<=s;a++)e.push(a);this.currentPage<this.totalPages-1&&e.push(m)}return e}getCurrentPage(){return this.currentPage}getTotalPages(){return this.totalPages}clear(){this.view.clear()}onPageChange(e){this.listeners.push(e)}notifyListeners(){this.listeners.forEach(e=>e(this.currentPage,this.itemsPerPage)),this.view.render()}}const D="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";class ${constructor(e,t,s,a){this.containerElement=e,this.paginationContainer=t,this.filter=s,this.itemsPerPage=a,this.init()}setFilter(e){this.filter=e,this.loadData()}clear(){var e;this.containerElement.innerHTML="",(e=this.pagination)==null||e.clear()}onCategorySelect(e){this.onCategorySelectCallback=e}init(){this.loadData(),this.initListeners(),this.initObservers()}initListeners(){this.containerElement.addEventListener("click",e=>{var a;const s=(a=e.target.closest("[data-type]"))==null?void 0:a.getAttribute("data-type");this.onCategorySelectCallback&&s&&this.onCategorySelectCallback(s)})}initObservers(){const e=new IntersectionObserver((a,n)=>{a.forEach(r=>{if(r.isIntersecting){const o=r.target;o.src=o.dataset.src||"",n.unobserve(o)}})});let t=[];new MutationObserver(a=>{for(const n of a)n.type==="childList"&&(t.forEach(r=>{e.unobserve(r)}),t=Array.from(this.containerElement.querySelectorAll("img[data-src]")),t.forEach(r=>{e.observe(r)}))}).observe(this.containerElement,{childList:!0,subtree:!1,attributes:!0})}async loadData(e=1,t=this.itemsPerPage){try{const s=await R({filter:this.filter,page:e,limit:t});this.updatePagination(s.totalPages,+s.page,+s.perPage),this.render(s.results)}catch(s){console.error("Error loading data:",s)}}updatePagination(e,t,s){this.pagination?(this.pagination.setTotalPages(e),this.pagination.setPage(t)):(this.pagination=new C(this.paginationContainer,e,s),this.pagination.onPageChange((a,n)=>{this.loadData(a,n)}))}createCategoryItem(e){return`
      <li class="exercise-category-card" data-type="${e.name}">
        <img
          class="exercise-category-image"
          src="${D}"
          data-src="${e.imgURL}"
          loading="lazy"
          alt="${e.name||"No name"}"
        />
        <div class="exercise-category-overlay" role="button" tabindex="0">
          <h3 class="exercise-category-title">${e.name}</h3>
          <p class="exercise-category-subtitle">${e.filter}</p>
        </div>
      </li>
    `}render(e){this.containerElement.innerHTML=e.filter(t=>t.name).map(this.createCategoryItem).join("")}}var h=(i=>(i.Muscles="Muscles",i.BodyParts="Body parts",i.Equipment="Equipment",i))(h||{});class k{constructor(e,t){this.config=e,this.currentCategory=t,this.currentFilter="",this.currentSearch="",this.config.searchInputElement=this.config.searchElement.querySelector("input"),this.config.searchResetElement=this.config.searchElement.querySelector('button[type="reset"]'),this.init()}onFilterChange(e){this.onChangeCallback=e}setCategory(e){this.currentCategory=e,this.currentFilter="",this.currentSearch="",this.render(),this.updateBreadcrumbs(),this.updateSearchForm(),this.emitChange()}getCategory(){return this.currentCategory}setFilter(e){this.currentFilter=e,this.updateBreadcrumbs(),this.updateSearchForm(),this.emitChange()}setSearch(e){this.currentSearch=e,this.emitChange()}init(){this.render(),this.initListeners()}initListeners(){var e;this.config.categoryFiltersElement.addEventListener("click",t=>{this.handleCategoryClick(t)}),this.config.searchElement.addEventListener("submit",t=>{this.handleSearchSubmit(t)}),this.config.searchElement.addEventListener("reset",()=>{this.handleSearchReset()}),(e=this.config.searchInputElement)==null||e.addEventListener("input",t=>{this.handleSearchInput(t)})}emitChange(){var e;(e=this.onChangeCallback)==null||e.call(this,this.currentCategory,this.currentFilter,this.currentSearch)}handleCategoryClick(e){const t=e.target;if(t.classList.contains("js-filter-btn")){const s=t.dataset.type;if(!s){console.error("No data type found.");return}this.setCategory(s)}}handleSearchSubmit(e){e.preventDefault();const s=new FormData(e.target).get("search");this.setSearch(s)}handleSearchReset(){this.currentSearch!==""&&(this.setSearch(""),this.updateSearchInput(""))}handleSearchInput(e){this.updateSearchInput(e.target.value)}updateSearchForm(){this.currentFilter?this.config.searchElement.classList.remove("hidden"):(this.config.searchElement.dispatchEvent(new Event("reset")),this.config.searchElement.classList.add("hidden"))}updateSearchInput(e){var t,s;e?(t=this.config.searchResetElement)==null||t.classList.remove("hidden"):(s=this.config.searchResetElement)==null||s.classList.add("hidden")}updateBreadcrumbs(){const e=this.config.breadcrumbsElement.querySelector(".breadcrumbs-splitter"),t=this.config.breadcrumbsElement.querySelector(".filter-value");e&&t&&(this.currentFilter!==""?(e.classList.remove("hidden"),t.classList.remove("hidden"),t.innerHTML=this.currentFilter):(e.classList.add("hidden"),t.classList.add("hidden"),t.innerHTML=""))}render(){this.config.categoryFiltersElement.innerHTML=Object.values(h).map(e=>{const t=e===this.currentCategory?"active":"",s=e.charAt(0).toUpperCase()+e.slice(1);return`
          <li>
            <button
              class="filter-btn js-filter-btn ${t}"
              data-type="${e}"
              type="button"
            >
              ${s}
            </button>
          </li>
        `}).join("")}}class O extends x{constructor(e,t,s,a="No exercises found"){super(e,!1,a),this.containerElement=e,this.paginationContainer=t,this.itemsPerPage=s,this.params={}}setParams(e){this.params=e,this.loadData(1,this.itemsPerPage)}clear(){var e;super.clear(),(e=this.pagination)==null||e.clear()}async loadData(e=1,t=this.itemsPerPage){try{const s=await T({...this.params,page:e,limit:t});this.updatePagination(s.totalPages,s.page,s.perPage),this.render(s.results)}catch(s){console.error("Error loading data:",s)}}updatePagination(e,t,s){this.pagination?(this.pagination.setTotalPages(e),this.pagination.setPage(t)):(this.pagination=new C(this.paginationContainer,e,s),this.pagination.onPageChange((a,n)=>{this.loadData(a,n)}))}}const j=async i=>(await S.post("/subscription",{email:i})).data;class H{constructor(e){this.form=e,this.form&&(this.submitButton=this.form.querySelector('button[type="submit"]'),this.init())}init(){this.form.addEventListener("submit",e=>this.handleSubmit(e))}async handleSubmit(e){var a,n;if(e.preventDefault(),!this.form)return;const s=new FormData(this.form).get("email");this.toggleButtonLoader(!0);try{const r=await j(s);E.success({message:r.message,position:"topRight"}),this.form.reset()}catch(r){await new Promise(L=>setTimeout(L,1e3));const o=r instanceof q?((n=(a=r.response)==null?void 0:a.data)==null?void 0:n.message)||"Error while sending subscription.":"An unexpected error occurred while sending the subscription.";E.error({message:o,position:"topRight"})}finally{this.toggleButtonLoader(!1)}}toggleButtonLoader(e){const t=this.submitButton.querySelector(".button-text"),s=this.submitButton.querySelector(".button-loader");e?(t==null||t.classList.add("hidden"),s==null||s.classList.remove("hidden")):(t==null||t.classList.remove("hidden"),s==null||s.classList.add("hidden"))}}const A=()=>window.innerWidth<768,_=`It appears that there are no any exercises for selected filters.
Try to change filters or search criteria.`,P=G(),p=V(),f=U();z();const y=new F("#exercise-modal-content"),b=new M("#exercise-rating-content"),N={[h.Muscles]:"muscles",[h.Equipment]:"equipment",[h.BodyParts]:"bodypart"};P.onFilterChange((i,e,t)=>{e?(f.setParams({[N[i]]:e,keyword:t}),p.clear()):(p.setFilter(i),f.clear())});p.onCategorySelect(i=>{P.setFilter(i)});const v=async i=>{y.show(i),y.onRatingOpen(e=>{b.show(e),b.onDialogClose(()=>{v(i)})})};f.onExerciseSelect(async i=>{const e=await I(i);v(e)});function G(){const i=document.querySelector(".js-category-filters"),e=document.querySelector(".js-breadcrumbs"),t=document.querySelector("#search-form");return new k({categoryFiltersElement:i,breadcrumbsElement:e,searchElement:t},h.Muscles)}function V(){const i=A()?9:12,e=document.querySelector(".exercise-categories-list"),t=document.querySelector(".js-categories-pagination");return new $(e,t,P.getCategory(),i)}function U(){const i=A()?8:10,e=document.querySelector(".exercise-cards-list"),t=document.querySelector(".js-items-pagination");return new O(e,t,i,_)}function z(){const i=document.querySelector(".subscribe-form");return new H(i)}
//# sourceMappingURL=index.js.map
