export enum Muscles {
  Abs = 'abs',
  Biceps = 'biceps',
  Pectorals = 'pectorals',
  SerratusAnterior = 'serratus anterior',
  Lats = 'lats',
  Adductors = 'adductors',
  Traps = 'traps',
  Triceps = 'triceps',
  Calves = 'calves',
  LevatorScapulae = 'levator scapulae',
  Quads = 'quads',
  CardiovascularSystem = 'cardiovascular system',
  Glutes = 'glutes',
  UpperBack = 'upper back',
  Abductors = 'abductors',
  Delts = 'delts',
  Forearms = 'forearms',
  Hamstrings = 'hamstrings',
  Spine = 'spine',
}
